### ISSUE TITLE
Snapshot compare fails when simulator running on external monitor.

### ISSUE THREAD

**Issue by BennettSmith** [pointfreeco/swift-snapshot-testing#551] opened 2021-12-20 04:05 UTC
I have a number of snapshot tests that will successfully complete multiple times when run on the same display, but fail when run on a different display. In my case, when the initial test snapshots are recorded while the simulator is running on my 5K LG external monitor then subsequent runs will pass.  However, if I disconnect the laptop from the external monitor and try to run the tests again they will fail.  Below is an example set of images showing the failed comparison.

Reference Image:

![test_CardButtonBDesign-iOS-13-Test-Device-250x68 1](https://user-images.githubusercontent.com/123463/146710140-4707e2d1-2ab1-42bb-9d3b-c59d73387b9f.png)

Test Image:

![test_CardButtonBDesign-iOS-13-Test-Device-250x68 1](https://user-images.githubusercontent.com/123463/146710238-72658d41-71b5-4fa1-a4da-fd7ee622f131.png)

Here is what Image Magick shows as the difference when comparing the images:

![difference](https://user-images.githubusercontent.com/123463/146710286-4e783f07-a374-4236-8dcc-91778d54a4ea.png)

It looks like an anti-aliasing issue with how the rounded rectangle is rendered.

Any suggestions on how to work around this?  Is there some setting I'm missing when capturing the snapshots?

**Comment by stephencelis** [comment] 2022-01-07 19:31
@BennettSmith There are a number of things that can cause images to render slightly differently, and this is unfortunately one of them. The best you can do is always run snapshot tests on a consistent environment, or change the `precision` argument on the snapshot strategy to allow for some pixel variation.

Going to close this out as it isn't an underlying bug with the library. If you'd like to continue the discussion, feel free to open one on the [forum](https://github.com/pointfreeco/swift-snapshot-testing/discussions)!

**Closed by stephencelis** 2022-01-07 19:31 UTC

**Comment by app-arianamini** [comment] 2023-09-11 11:59
The issue is, adding (changing) precision makes the test take x6-x10 times longer, that means more pipeline costs.
Furthermore, we cannot adjust the pipeline logic (display) if it has at all any displays.
