### ISSUE TITLE
False positive assertion when comparing reference with empty image

### ISSUE THREAD

**Issue by nuno-vieira** [pointfreeco/swift-snapshot-testing#454] opened 2021-04-08 18:59 UTC
### Bug Description
Unfortunately in the project that I'm working on, we encountered some false positives, where we thought that the tests were actually working, but they were not. What happened was that after some refactorings, some of the tests passed, but actually, the new reference images had no size at all but the framework assumed that everything was okay. So there's a bug when the framework compares the current reference image with the empty red generated image.

I've opened a PR with the fix here: https://github.com/pointfreeco/swift-snapshot-testing/pull/453

**Comment by stephencelis** [comment] 2021-08-16 23:15
I think this is a dupe of #414

**Comment by nuno-vieira** [comment] 2021-08-17 01:05
> I think this is a dupe of #414

Yes, it seems it is, sorry! Feel free to close this one or the #414 👍

**Comment by stephencelis** [comment] 2021-08-17 01:15
It's a good report, regardless! Thanks! We're working through a backlog now so just trying to focus our efforts :) Closing in favor of the original.

**Closed by stephencelis** 2021-08-17 01:15 UTC
