### ISSUE TITLE
Snapshots on Apple Silicon devices

### ISSUE THREAD

**Issue by luisrecuenco** [pointfreeco/swift-snapshot-testing#424] opened 2021-01-28 13:41 UTC
It seems that Apple Silicon machines generate snapshots that are slightly different from the ones generated on x86 machines. The problem is very similar to the one where the very same simulator generates different images depending on the OS version.

The issues persist when running the simulator using Rosetta.

Taking into account that it’ll be quite common in the near future to have a team of developers with Intel and Apple Silicon architectures… What’s the best way to handle it?

Thanks

**Comment by ldstreet** [comment] 2021-02-04 15:07
One possible (bad) solution could be to allow for snapshot variants based on architecture. Unfortunately, this would mean recording multiple times which would almost certainly become a nightmare.

**Comment by gobetti** [comment] 2021-02-04 18:52
this and a few other open issues seem to be duplicates of https://github.com/pointfreeco/swift-snapshot-testing/issues/313 but knowing of more scenarios leading to the same error is great for prioritizing. I've also recently upgraded to an M1 and can confirm the difference image has pixels off most usually by 1, which isn't visible in the image itself (looks plain black) but post-filtering with a simple Threshold tool will reveal those pixels

**Comment by jjatie** [comment] 2021-02-05 15:32
I have implemented a custom assertSnapshot in the referenced PR above for anyone needing to work in Silicon/Intel mixed teams. You can find it [here](https://github.com/danielgindi/Charts/pull/4574/files#diff-0d32a7d53d8fd03be1ffad9d1ec32e012e94cc23c3c299665402fec709f1832b) on line 22.

While I don't think it's a good solution, I don't know what a better alternative would be.

**Comment by voidless** [comment] 2021-02-08 16:02
In my case snapshots began rendering identically under Apple Silicon after I added 'Host Application' for unit test targets.
Currently we use iOS 14.2 simulator for unit tests, there are rendering differences with 14.4.

I had to use Rosetta because Xcode 12.4 running under Rosetta can't launch unit tests without host app.
We run Xcode under Rosetta because we currently have 9 dependencies that don't support Apple Silicon

Before that I considered adding precision:0.99 to asserts, but it's also not a good solution. In my case there were differences in rounded corners clipping

**Comment by luisrecuenco** [comment] 2021-02-09 06:48
Hey @voidless. Interesting to know about the "Host Application" fixing the issue. Unfortunately, the "Host Application" cannot be always used, so I'm afraid that's not an option for a lot of us.

**Comment by voidless** [comment] 2021-02-09 11:59
Can you give an example? We use host apps generated by cocoapods, they only have almost empty appdelegate.m, main.storyboard files and info.plist and are linked with the corresponding framework.

**Comment by luisrecuenco** [comment] 2021-02-09 12:13
I guess that could work, but I wonder if there's an easier way not to add all that noisy and cumbersome infrastructure (even if Cocoapods automates part of that). Also, AFAIK, you cannot have a host app for Swift Packages...

**Comment by nuno-vieira** [comment] 2021-02-24 16:10
We have this issue only when rendering shadows. We were having this issue on a view that has a drop shadow. After removing the drop shadow from the view [here](https://github.com/GetStream/stream-chat-swift/pull/833/commits/9dbf4951130847823d9efe73f3d2a54556379085), it works the same for both M1 and Intel. Still could not really understand why nor how to fix it yet 😞

**Comment by Tovkal** [comment] 2021-06-10 16:24
We also have a team with a mix of Intel and M1, plus our CI is now Intel but it is bound to be M1 someday. We were already using Host Application, we tried different iOS versions, tried with and without Rosetta both on Xcode.app and Simulator.app without any luck. Having different snapshots for each architecture would not work for us, as people with an M1 can't generate snapshots for Intel and viceversa, and that would be bound to fail in CI.

We opted to temporarily (until we are all using arm64) lower the `precision`, so small changes won't fail, by creating a new Snapshotting called `.impreciseImage`. Here's a [gist](https://gist.github.com/Tovkal/0eeb8169b4b1f53a5c0896e5645b7656) in case somebody wants to try it.

**Comment by ShayanPapershift** [comment] 2021-06-21 16:12
We also have the same problem when using shadowOpacity. tests are failing, we also changed the precious but not working

**Comment by JWStaiert** [comment] 2021-06-22 22:57
I submitted a pull request adding a fuzzy compare implemented in objective-c which is 30 times faster than the vanilla matcher under worst-case conditions (all pixels compared.) This matcher will report failure if any pixel component absolute difference exceeds a user provided maximum -OR- if the average pixel component absolute difference exceeds a user provided maximum. Only CGImage, NSImage, and UIImage are supported but I will be adding fuzzy compare for other matchers soon.

**Comment by grigorye** [comment] 2021-09-17 12:16
> In my case snapshots began rendering identically under Apple Silicon after I added 'Host Application' for unit test targets.

I'm not 100% sure, but in our case we get differences in rendering some custom icon even when using host apps.

**Comment by grigorye** [comment] 2021-09-17 13:02
I wonder if any kind of solution that employs imprecise matching would result in loads of "modified" snapshots generated every time they re-recorded on a "mismatching" platform: as far as I understand, there's currently no way to avoid recording a new variant of a snapshot if the new version of the snapshot still fuzzy matches the original:

To re-record automatically, we delete the snapshots and run the tests - there's no chance in this case that fuzzy matching would prevent recording of new versions... OTOH, when "re-recording" manually, I can pass `record: true` to `assertSnapshot`, but as far as I understand, the current implementation of the `assertSnapshot` does not do any matching in this case either. But if it did the matching, and only recorded the snapshot if it does not match (according to the given matcher), this would be probably a solution for the above problem?

Overall, how do you people handle recording of imprecisely matching snapshots in general?

**Comment by mcaylus** [comment] 2021-11-10 09:43
> I submitted a pull request adding a fuzzy compare implemented in objective-c which is 30 times faster than the vanilla matcher under worst-case conditions (all pixels compared.) This matcher will report failure if any pixel component absolute difference exceeds a user provided maximum -OR- if the average pixel component absolute difference exceeds a user provided maximum. Only CGImage, NSImage, and UIImage are supported but I will be adding fuzzy compare for other matchers soon.

Any update on this? Do you have a branch you can refer to for this work?

**Comment by Namedix** [comment] 2021-11-19 15:05
Is there a chance that this can be addressed somehow?

**Comment by codeman9** [comment] 2021-12-07 17:37
I've found that forcing the snapshots to be taken in sRGB seems to work. I do this in the device descriptions:

```swift
  public static func iPhoneSe(_ orientation: ViewImageConfig.Orientation)
    -> UITraitCollection {
      let base: [UITraitCollection] = [
        .init(displayGamut: .SRGB),
        .init(forceTouchCapability: .available),
        .init(layoutDirection: .leftToRight),
        .init(preferredContentSizeCategory: .medium),
        .init(userInterfaceIdiom: .phone)
      ]
...

  public static func iPhone8Plus(_ orientation: ViewImageConfig.Orientation)
    -> UITraitCollection {
      let base: [UITraitCollection] = [
        .init(displayGamut: .SRGB),
        .init(forceTouchCapability: .available),
        .init(layoutDirection: .leftToRight),
        .init(preferredContentSizeCategory: .medium),
        .init(userInterfaceIdiom: .phone)
      ]
...
```

Has anyone else tried this?

**Comment by Tovkal** [comment] 2021-12-28 11:04
> I've found that forcing the snapshots to be taken in sRGB seems to work. I do this in the device descriptions:
> 
> ```swift
>   public static func iPhoneSe(_ orientation: ViewImageConfig.Orientation)
>     -> UITraitCollection {
>       let base: [UITraitCollection] = [
>         .init(displayGamut: .SRGB),
>         .init(forceTouchCapability: .available),
>         .init(layoutDirection: .leftToRight),
>         .init(preferredContentSizeCategory: .medium),
>         .init(userInterfaceIdiom: .phone)
>       ]
> ...
> 
>   public static func iPhone8Plus(_ orientation: ViewImageConfig.Orientation)
>     -> UITraitCollection {
>       let base: [UITraitCollection] = [
>         .init(displayGamut: .SRGB),
>         .init(forceTouchCapability: .available),
>         .init(layoutDirection: .leftToRight),
>         .init(preferredContentSizeCategory: .medium),
>         .init(userInterfaceIdiom: .phone)
>       ]
> ...
> ```
> 
> Has anyone else tried this? May not be ideal for the final fix, but might be a clue.

I tried setting just the `displayGamut` trait, recorded all snapshots on an M1 and they failed on an Intel 🙁

**Comment by ArielDemarco** [comment] 2022-01-05 19:36
We tried to use less `precision` but some of the snapshots failed (even with `0.9` 😓 ). We also tried using `UITraitCollection(displayGamut: .SRGB)` but it didn't work at all. 
So, in order to make easier our lives while we develop both using Intel and Apple Silicon we decided to remove all the shadows on our snapshot tests. As we didn't want to add this validation to the codebase that we deliver to production (through environment variables or preprocessor flags), we've used Swizzling only on the test target:
```swift
extension CALayer {
    static func swizzleShadow() {
        swizzle(original: #selector(getter: shadowOpacity), modified: #selector(_swizzled_shadowOpacity))
        swizzle(original: #selector(getter: shadowRadius), modified: #selector(_swizzled_shadowRadius))
        swizzle(original: #selector(getter: shadowColor), modified: #selector(_swizzled_shadowColor))
        swizzle(original: #selector(getter: shadowOffset), modified: #selector(_swizzled_shadowOffset))
        swizzle(original: #selector(getter: shadowPath), modified: #selector(_swizzled_shadowPath))
    }
    
    private static func swizzle(original: Selector, modified: Selector) {
        let originalMethod = class_getInstanceMethod(self, original)!
        let swizzledMethod = class_getInstanceMethod(self, modified)!
        method_exchangeImplementations(originalMethod, swizzledMethod)
    }
    
    @objc func _swizzled_shadowOpacity() -> Float { .zero }
    @objc func _swizzled_shadowRadius() -> CGFloat { .zero }
    @objc func _swizzled_shadowColor() -> CGColor? { nil }
    @objc func _swizzled_shadowOffset() -> CGSize { .zero }
    @objc func _swizzled_shadowPath() -> CGPath? { nil }
}
```
**Important**: as we work in a framework, we had to create a class that acts as the `NSPrincipalClass` of the test bundle so the swizzle is called once. Something like this:
```swift
final class MyPrincipalClass: NSObject {
    override init() {
        CALayer.swizzleShadow()
    }
}
```
Note that after declaring the principal class, in order for it to work, you should add it to the `Info.plist` of test bundle:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
       ...
       ...
        <key>NSPrincipalClass</key>
	<string>NameOfTheTestBundle.MyPrincipalClass</string>
</dict>
</plist>
```

**Comment by Iron-Ham** [comment] 2022-01-07 20:19
I've gone ahead and forked the repo to create a new release: https://github.com/Iron-Ham/swift-snapshot-testing

Key difference is the output structure of the project.
Instead of outputting:

```
__Snapshots__/TestClass/myFunctionName.swift
```
We now output:
```
Snapshots/PLATFORM/__Snapshots__/TestClass/myFunctionName-PLATFORM.swift
```
Where PLATFORM == arm64 or intel.

This is intended to be used with a GitHub action that detects changes in the arm64 directory in order to create new snapshots for the intel directory (or vice-versa, when GitHub Actions supports arm64 builds). 

Maybe with a few changes this could be a good candidate for merging back upstream. At present, using this means that you'll have to re-record your snapshots, which could be a pretty destructive diff.

**Comment by Iron-Ham** [comment] 2022-01-07 21:11
I found the fix for this. It's not ideal, but it seemingly works:

Run both Xcode and the Simulator in Rosetta.

**Comment by codeman9** [comment] 2022-01-10 19:58
> I've found the fix for this. It's not ideal, but it seemingly works for the moment: Run both Xcode and the Simulator in Rosetta. To run your simulator in Rosetta, right click on Xcode and choose "Show Package Contents", from there you navigate to "Contents > Developer > Applications," There you'll find the Simulator app. If you right click on it and choose "Get Info", you'll find an option to run it using Rosetta.
> 
> This has been sufficient for our >1,000 snapshot tests at GitHub, across app targets and frameworks/modules.

I tried this and some snapshots still fail for me. :(

**Comment by ldstreet** [comment] 2022-01-11 15:36
My company created a script that downloads any failed snapshots from a CI build to your local working copy and places them in the correct directories. This kind of script is very useful for many reasons, but in this scenario you could have a workflow where:

1) Write your code and record snapshots locally with Intel
2) Run CI remotely with Apple Silicon
3) Run script to download all failed snapshots
4) Manually commit/push all valid updates.

This way you only have one set of snapshots all with Apple Silicon as the source of truth. As more developers move their machines to arm64 they can record locally, but I've found even in that scenario its still useful to have the option to download from CI.

**Comment by grigorye** [comment] 2022-01-11 15:41
@ArielDemarco
>We tried to use less precision but some of the snapshots failed (even with 0.9 😓 )

I can only recommend take a look at this, that's a fuzzy comparator by @JWStaiert that properly accounts image nature of the snapshots: https://github.com/JWStaiert/SnapshotTestingEx. (See https://github.com/pointfreeco/swift-snapshot-testing/issues/424#issuecomment-866390494 for the details). As far as I can recall, the thing is that, by default, the precision is meant to account the *number* of different "pixels", not the difference in the "pixel values". The fuzzy comparator changes that for the better.

We successfully using it together with the [patch](https://github.com/pointfreeco/swift-snapshot-testing/pull/519/files#diff-08d4ec82efad472f5aa91084340fa360207c1f3ebcdea9bf4859cfe96a9a9ef8) (see https://github.com/pointfreeco/swift-snapshot-testing/issues/424#issuecomment-921778987)  that provides a solution for avoiding overwriting the snapshots if they're fuzzy matching.

**Comment by alrocha** [comment] 2022-01-24 20:15
My personal update and fixes: no idea if someone has said some of these that I am going to mention sorry for repetition if is the case, I have been reading a lot of stuff lately on how to fix it. 

Current scenario: in the project I work for, CI Intel github actions, the iOS team is changing to M1 and I was the first one getting it (being the last one would saved me many headackes 😄), all the tests recorded are recorded with Intel machines, ~10% failing in the M1, and the new tests recorded with M1, fails in CI. 

What I tried:
* Snapshot test with precission to 0.99 works in many cases, is like adding tolerance in FBSnapshotTest library. **It works** mainly the diff between tests was a tiny shadow so this approach could have been valid, unfortunately someone from the team didn't like it so I kept researching.
* Record snapshots in M1 with Rosetta, Xcode and Simulator both in rosetta mode, this approach **works** tests would pass on intel CI (since they will be recorded in a x86_64 arch)
* Looks like SwiftUI Views wrapped with UIViewRepresentable have some sort of issue, with the compatibility, still trying to finde a solution like this.

Looks like mainly tests with shadows `shadowOpacity` are the ones that are failing. 

Tried out the modify the `UITraitColleciton` extension with `.sRGB` didn't work in my case. 

Hope it helps someone, cheers!

**Comment by lukeredpath** [comment] 2022-01-26 11:22
We're also having this problem as we start transitioning developer devices to Apple Silicon, while some of us are still going to be on Intel for a while longer. There are really two issues at play here:

* Where the snapshots are generated originally.
* Where the snapshots are verified.

Any solutions involving standardising where these things happen is difficult to achieve - some developers will be on Intel by choice, some are on M1. Our CI currently only supports Intel and we have no ETA on Apple Silicon support. That leaves us with needing to be able to verify snapshots accurately on Intel machines.

Of course, if snapshots need to always be verifiable on Intel, that means we cannot generate snapshots on Apple Silicon machines, which makes life very difficult for developers on M1s as they cannot generate new or updated snapshots unless we can find some kind of automated way (like a Github Action) that re-generates new and updated snapshots on an Intel executor and re-commits them. This is currently an option we're considering but I'd prefer to avoid this.

I think the best solution to this problem is a revised image diffing strategy that can account for minor differences between the two architectures. We have tried adjusting the precision with mixed results - sometimes it makes a test pass, sometimes it does not. Additionally, it seems that changing the precision has a serious impact on performance - I've seen a fairly big test with 10 snapshots take 10x longer by changing the precision from 1.0 to 0.99 - it took over 40 seconds!

I'd like to try the SnapshotTestingEx solution above but unfortunately it looks like this needs a patched version of SnapshotTesting - it would be great to get some movement on this. I'm curious if @stephencelis or @mbrandonw have run into this issue in their own apps and if they've found a solution.

**Comment by Deco354** [comment] 2022-01-26 13:14
You can change the testname so you record different images based on your devices architecture.

```swift
        var testID = identifier
        Architecture.isArm64 || Architecture.isRosettaEmulated {
            testID.append("-arm64")
        }
        
            assertSnapshot(matching: view,  testName: testID)
```

```swift

import Foundation

@objc(PSTArchitecture) public class Architecture: NSObject {
    /// Check if process runs under Rosetta 2.
    /// https://developer.apple.com/forums/thread/652667?answerId=618217022&page=1#622923022
    /// https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment
    @objc public class var isRosettaEmulated: Bool {
        // Issue is specific to Simulator, not real devices
        #if targetEnvironment(simulator)
        return processIsTranslated() == EMULATED_EXECUTION
        #else
        return false
        #endif
    }
    
    /// Returns true on M1 macs and false on intel machines or M1 macs using Rosetta
    public static var isArm64: Bool {
        #if arch(arm64)
        return true
        #else
        return false
        #endif
    }
}

fileprivate let NATIVE_EXECUTION = Int32(0)
fileprivate let EMULATED_EXECUTION = Int32(1)
fileprivate let UNKNOWN_EXECUTION = -Int32(1)

private func processIsTranslated() -> Int32 {
    let key = "sysctl.proc_translated"
    var ret = Int32(0)
    var size: Int = 0
    sysctlbyname(key, nil, &size, nil, 0)
    let result = sysctlbyname(key, &ret, &size, nil, 0)
    if result == -1 {
        if errno == ENOENT {
            return 0
        }
        return -1
    }
    return ret
}

```

**Comment by olejnjak** [comment] 2022-01-27 08:20
For me the solution was to exclude ARM64 architecture for simulator by using `EXCLUDED_ARCHS[sdk=iphonesimulator*] = "arm64"` build setting, it effectively forces app to run in Rosette while Xcode and simulator still run natively. I had some issues with SPM dependencies but I was able to migrate them to Carthage.

**Comment by MariusDeReus** [comment] 2022-02-01 15:24
Same problem here for tests in a Mac application. Not only NSViews render different, even CoreGraphics rendering of NSImages is different on M1 compared to Intel.
I had this issue before between an Intel developer machine (with P3 screen) and a headless Mac mini in CI. But that was to a lesser degree and with a tolerance of 0.99 all succeeded. 
But between M1 and Intel some even still fail with 0.92. So that is too much tolerance for a meaningful test.
Because this is a Mac app, I cannot play with simulator settings or things like that.

**Comment by ernichechelski** [comment] 2022-02-09 09:56
Maybe this solution would be useful. Gives pretty promising and consistent output on Intel and m1 as well. Created with @karolpiateknet

```
import SnapshotTesting
@testable import YourProject
import SwiftUI
import XCTest

enum ContentSizeMode {
    /// Content is checked by its intrinsic content width.
    case horizontal
    /// Content is checked by its intrinsic content height.
    case vertical
    /// Content is checked by its intrinsic content size.
    case both
    /// Content is aligned to the screen dimensions.
    case none
}

/// Asserts that a given value matches a reference on disk.
/// Uses intrinsicContentSize height to test proper height of the element.
///
/// - Parameters:
///   - view: a view to be snapshot tested.
///   - name: An optional description of the snapshot.
///   - recording: Whether or not to record a new reference.
///   - timeout: The amount of time a snapshot must be generated in.
///   - contentSizeMode: You can choose which intrinsicContentSize axis should be taken into account. Default is vertical
///     as most components are aligned horizontally to the screen but have intrinsic height.
///   - precision: Default is 98 percent to make sure that color differences on m1 and intel doesn't fail snapshot tests.
///     As images are compared by just its raw data, the precision just describes the percentage of matched data (the docs says pixels, but imho is oversimplified description).
///   - file: The file in which failure occurred. Defaults to the file name of the test case in which this function was called.
///   - testName: The name of the test in which failure occurred. Defaults to the function name of the test case in which this function was called.
///   - line: The line number on which failure occurred. Defaults to the line number on which this function was called.
func assertSnapshot<Content: View>(
    view: Content,
    named name: String? = nil,
    record recording: Bool = false,
    timeout: TimeInterval = 5,
    contentSizeMode: ContentSizeMode = .vertical,
    precision: Float = 0.98,
    file: StaticString = #file,
    testName: String = #function,
    line: UInt = #line
) {
    let deviceWidth = ViewImageConfig.iPhone8.size?.width ?? 0
    let deviceHeight = ViewImageConfig.iPhone8.size?.height ?? 0

    let finalView: AnyView
    switch contentSizeMode {
    case .horizontal:
        finalView = AnyView(view.frame(height: deviceHeight))
    case .vertical:
        finalView = AnyView(view.frame(width: deviceWidth))
    case .both:
        finalView = AnyView(view)
    case .none:
        finalView = AnyView(view.frame(width: deviceWidth, height: deviceHeight))
    }

    let hostingController = UIHostingController(
        rootView: finalView.ignoresSafeArea()
    )

    let intrinsicContentWidth = hostingController.view.intrinsicContentSize.width
    let intrinsicContentHeight = hostingController.view.intrinsicContentSize.height
    var snapshotSize: CGSize
    switch contentSizeMode {
    case .horizontal:
        snapshotSize = CGSize(
            width: intrinsicContentWidth,
            height: deviceHeight
        )
    case .vertical:
        snapshotSize = CGSize(
            width: deviceWidth,
            height: intrinsicContentHeight
        )
    case .both:
        snapshotSize = CGSize(
            width: intrinsicContentWidth,
            height: intrinsicContentHeight
        )
    case .none:
        snapshotSize = CGSize(
            width: deviceWidth,
            height: deviceHeight
        )
    }
    let failure = verifySnapshot(
        matching: hostingController,
        as: .image(
            precision: precision,
            size: snapshotSize == .none ? nil : snapshotSize
        ),
        named: name,
        record: recording,
        timeout: timeout,
        file: file,
        testName: testName,
        line: line
    )
    guard let message = failure else { return }
    XCTFail(message, file: file, line: line)
}
```

**Comment by pimms** [comment] 2022-02-09 12:43
We worked around this issue a few weeks ago by allowing sub-pixels to deviate by a certain amount, as we were struggling with shadows, corner radii, and color-space differences. Instead of using `precision: 0.9` _(requiring 90% of the pixels to match 100%)_, we now use `precision: 1, pixelDiffThreshold: 5` _(requiring 100% of the subpixels to deviate no more than 5 values from the reference)_.

I meant to open a PR back then, but it seems like I forgot about it. I'll do it if there's any interest.

https://github.com/pimms/swift-snapshot-testing

**Comment by lukeredpath** [comment] 2022-02-09 12:45
@pimms what is the performance of your solution like? We've noted that lowering the precision below 1 incurs a 10x performance penalty due to the pixel diffing - does yours have a similar penalty?

**Comment by pimms** [comment] 2022-02-09 13:01
@lukeredpath No, we ended up compiling `SnapshotTesting` _(and only `SnapshotTesting`)_ with `-O`.

<details>
<summary>Longer explanation<summary>
We noticed that at one point too _(after the M1 transition I believe?)_, and found out that it was caused by how range-iterations works when compiled without optimization. If I recall correctly, the unoptimized x86 code was a couple of orders of magnitude slower than ARM, causing our CI-builds to take forever.

This loop is the offender:
https://github.com/pointfreeco/swift-snapshot-testing/blob/main/Sources/SnapshotTesting/Snapshotting/UIImage.swift#L105
```
  // Gets chewed into horribly slow code
  for byte in 0..<byteCount { /* snip */ }

  // wicked quick m8
  var byte = 0
  while byte < byteCount { /* snip */ }
```

I can't remember the details, but we ended up adding this to our Podfile.
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "SnapshotTesting"
            target.build_configurations.each do |config|
                xcconfig_path = config.base_configuration_reference.real_path
                puts "Setting optimization flags on #{xcconfig_path}..."
                File.open(xcconfig_path, "a") {|file|
                  file.puts 'SWIFT_OPTIMIZATION_LEVEL = -O'
                  file.puts 'GCC_OPTIMIZATION_LEVEL = 3'
                }
            end
        end
    end
end
```
</details>

**Comment by lukeredpath** [comment] 2022-02-09 13:40
Thank you, would love it if you could open a PR for your pixel diffing strategy too.

**Comment by pimms** [comment] 2022-02-09 13:57
@lukeredpath I combined the subpixel thresholding into the PR 👍

**Comment by choulepoka** [comment] 2022-04-03 12:49
We have basically used @pimms fork with great success, it is still a wonder to me why it is not merged yet, because it does get the job done, without a performance penalty.

**Comment by acecilia** [comment] 2022-04-14 00:36
One alternative solution, maybe useful for somebody. The best way to work around this issue for me was to directly avoid supporting both M1 and intel, and instead perform the snapshot testing on CI exclusively in M1 machines

**Comment by choulepoka** [comment] 2022-04-19 14:58
@acecilia This does indeed would solve the issue. However, it is not feasible for the time being, because our CI/CD is running on Github, which is Intel-Based for the foreseeable future.

We have switched to a self-hosted runner for performance reason, but AWS is not giving access to M1-Based Mac-Minis to the general public yet, we're still stuck with a Intel-based machine for now.

**Comment by westerlund** [comment] 2022-04-19 17:16
@choulepoka @acecilia self-hosted runners are not supported on M1 hardware yet.
https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#architectures

**Comment by tahirmt** [comment] 2022-04-19 20:56
It's easy to get out of rosetta and run the builds natively by just doing `arch -arm64 ...` to run xcodebuild natively.

**Comment by gistya** [comment] 2022-05-25 14:19
Any idea _why_ this is happening? I.e. why does the same simulator produce different snaps based on whatever the current hardware is?

Is it due to differences in the color space actively selected? I.e. if all Macs have their display set to Generic RGB Profile, does this help? 

If not, doesn't this represent a bug in iOS simulator that Apple should fix? I cannot understand why the simulation would differ on this detail based on the host hardware.

**Comment by keith** [comment] 2022-05-25 19:31
It sounds like all bets are off when rendering across architectures as they can theoretically go through entirely different rendering pipelines.

**Comment by carsten-wenderdel** [comment] 2022-05-31 06:57
> @choulepoka @acecilia self-hosted runners are not supported on M1 hardware yet.
> https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#architectures

There now is a prerelease of the runner software with Apple Silicon support: https://github.com/actions/runner/releases/tag/v2.292.0

**Comment by Motobard** [comment] 2022-06-15 11:27
> I submitted a pull request adding a fuzzy compare implemented in objective-c which is 30 times faster than the vanilla matcher under worst-case conditions (all pixels compared.) This matcher will report failure if any pixel component absolute difference exceeds a user provided maximum -OR- if the average pixel component absolute difference exceeds a user provided maximum. Only CGImage, NSImage, and UIImage are supported but I will be adding fuzzy compare for other matchers soon.

I was unable to find it. Can you provide us with a pointer?

**Comment by markst** [comment] 2022-06-15 11:30
> I was unable to find it. Can you provide us with a pointer?
was this it? - https://github.com/pointfreeco/swift-snapshot-testing/pull/481

**Comment by JWStaiert** [comment] 2022-06-17 00:11
#490, https://github.com/pointfreeco/swift-snapshot-testing/pull/490

**Comment by jlcvp** [comment] 2022-06-22 16:06
Testing with a empty screen with navigation bar and bottom bar with some icons, the image diffs between our M1 Macs and our Intel ones are on the SFSymbols buttons we use on the botton bar about 2~3 pixels on each one. Setting the `precision` to 0.99 make it work as intended for now. 

I'll be following this discussion to see if we can figure out a better solution

**Comment by ejensen** [comment] 2022-09-12 15:15
https://github.com/pointfreeco/swift-snapshot-testing/pull/628 should resolve this issue with a new perceptual difference calculation. The small differences in Intel/Apple Silicon hardware accelerated anti-aliasing/shadows/blur rendering are under the [2% DeltaE value which is nearly imperceivable by the human eye](http://zschuessler.github.io/DeltaE/learn/#toc-defining-delta-e). Using a `perceptualPrecsion` value of >=98% will prevent imperceivable differences from failing assertions while noticeable differences are still caught.

**Closed** 2022-09-21 21:33 UTC

**Comment by simondelphia** [comment] 2023-01-18 22:10
@ejensen 

Note even with perceptual precision, if you re-record snapshots that were originally recorded on an Intel device on an Apple Silicon device, you will often get updated snapshots (with imperceptible differences) in your git diff, which is not ideal because then it's not clear whether the differences are due to actual changes or just the different chips. 

Is there any fix for that?

**Comment by ldstreet** [comment] 2023-01-18 22:18
@simondelphia isn't this true of any test that uses precision? I'd think failing tests should be your guide on whether or not to re-record, not git diffs. No?

**Comment by simondelphia** [comment] 2023-01-18 22:25
When you have `isRecording` enabled, any difference in the resulting snapshot shows up as a git diff. I generally re-record all snapshots in my project because a change may affect snapshots I did not anticipate. I suppose I could run tests with `isRecording` disabled, then only re-record the failing ones, but that's a lot of extra work.

**Comment by simondelphia** [comment] 2023-01-18 22:35
Also sometimes we get snapshot tests that pass even though they shouldn't, which I suppose is because the perceptual precision is below 1 (necessary for the CI), so ultimately we have to re-record frequently.

**Comment by ArielDemarco** [comment] 2023-03-20 13:03
> Did you see a noticeable drop-off in performance (test suite taking significantly longer) after applying this workaround Ari?

No, not at all when we measured it! To be honest, I think in some cases it might improve the performance because there's almost no overhead in rendering the shadows. On the other hand, I don't think any increase/drop-off in performance should be noticeable.

**Comment by pylapp** [comment] 2025-02-18 15:50
Got the same type of issue.
I defined the _precision_ to 0.96 and the _perceptualPrecision_ to 0.97 and it worked like a charm!
