### ISSUE TITLE
SwiftUI Picker Wheel Style Render seems broken

### ISSUE THREAD

**Issue by DanKorkelia** [pointfreeco/swift-snapshot-testing#548] opened 2021-12-13 15:34 UTC
Xcode 13.2 RC 
iOS 15

Observed the same issue on iOS 14.5 Simulator too.

<img width="667" alt="test 1" src="https://user-images.githubusercontent.com/31965092/145840433-a4d81ac3-a520-42d8-b0fd-3cdadeeb7c0b.png">

Added image to show the snapshot test result

Test
`   
func test() {
        
        assertSnapshot(
            matching: ContentView(),
            as: .image(layout: .device(config: .iPhone8(.landscape))),
            record: true
        )
    }
`

View
`
struct ContentView: View {
    private var options = ["Option 1", "Option 2", "Option 3"]
    @State private var selectedIndex = 0
    
    var body: some View {
        VStack {
            
            Text("Selection")
                .font(.title3)
            
            Picker(selection: $selectedIndex, label: Text("Options")) {
                ForEach(0 ..< options.count) {
                    Text(self.options[$0])
                }
            }
            
            .pickerStyle(.wheel)
        }
   
`

**Comment by DanKorkelia** [comment] 2021-12-14 10:11
Observed same issue in when setting trait to use dark mode.
I also attempted to set a background as it looks like some sort of transparency issue but no luck there.

**Comment by stephencelis** [comment] 2022-01-07 19:40
@DanKorkelia Can you elaborate as to what the issue is? The snapshot looks reasonable to me.

**Comment by DanKorkelia** [comment] 2022-01-07 21:46
@stephencelis Hey. Thank you for reply. I was under impression the snapshot should look the same as on screen appearance. Without grey gradient shading.

**Comment by stephencelis** [comment] 2022-01-08 00:01
@DanKorkelia That "gray" appears to be background opacity, which doesn't appear in the preview (or in this GitHub issue, when in light mode). Here's the image open in an editor that shows a checked grid where the background is transparent:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/658/148621827-8b5fabea-da83-4c23-9809-0da055c781e2.png">

In a preview/simulator the background is white so it renders normally. Because of this, I don't think this is an issue with the library, but rather a gotcha with how that view is rasterized. Some folks may have ideas on how to work around the issue, though, so please feel free to [start a discussion](https://github.com/pointfreeco/swift-snapshot-testing/discussions), instead!

**Comment by stephencelis** [comment] 2022-01-08 15:50
I'm going to close this out for now, since it doesn't appear to be a bug in the library. Thanks!

**Closed by stephencelis** 2022-01-08 15:50 UTC
