### ISSUE TITLE
iPhone Xr screenshot has wrong size

### ISSUE THREAD

**Issue by zlib** [pointfreeco/swift-snapshot-testing#332] opened 2020-05-07 07:26 UTC
Actually it is the same as iPhone XsMax.

**Comment by stephencelis** [comment] 2020-05-07 15:58
@zlib Could you provide more information on what the current behavior is and what you expect it to be? We'd also welcome a PR! These values are all defined here: https://github.com/pointfreeco/swift-snapshot-testing/blob/dcaeca0b80d2efdd881c67cdd62f7478fc5bec9f/Sources/SnapshotTesting/Common/View.swift#L15

So you should be able to edit the file and submit a PR quite easily 😄

**Comment by philippec** [comment] 2020-05-26 02:42
@zlib I'mn not sure this is an issue.  I just looked at the tech specs:

iPhone XR  is 1792-by-828-pixel resolution at 326 ppi
iPhone XsMax is 2688‑by-1242‑pixel resolution at 458 ppi

Since iPhone XR is 2x and iPhone XsMax is 3x, they both have the same number of points: 896 x 414, which is what you will find in `ViewImageConfig`.

Source:

https://www.apple.com/iphone-xr/specs/

https://support.apple.com/kb/SP780?viewlocale=en_US&locale=en_US

**Comment by stephencelis** [comment] 2021-08-16 21:28
Going to close this, since it seems to be working as intended!

**Closed by stephencelis** 2021-08-16 21:28 UTC
Labels: good first issue
