### ISSUE TITLE
How to take snapshot test after animation

### ISSUE THREAD

**Issue by Wanjing-Li** [pointfreeco/swift-snapshot-testing#383] opened 2020-09-11 08:56 UTC
Hey guys,

 I need do some snapshot test after my UIView animation finished, and these tests should run into several devices automatically.

I noticed there is a `Async<UIImage>` in source code, and I tried to extension `Snapshotting` and implemented my `image` methond:
```
extension Snapshotting where Value == UIViewController, Format == UIImage {
  
  public static func image(on config: SnapshotTesting.ViewImageConfig, precision: Float = 1, size: CGSize? = nil, traits: UITraitCollection = .init(), isAsync: Bool) -> Snapshotting {
      return Snapshotting(pathExtension: "png", diffing: .image, asyncSnapshot: { vc in
          Async<UIImage> {callback in
            DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
               UIGraphicsBeginImageContextWithOptions(vc.view.bounds.size, false, UIScreen.main.scale)

                   // Draw view in that context
                   vc.view.drawHierarchy(in: vc.view.bounds, afterScreenUpdates: true)

                   // And finally, get image
                   let image = UIGraphicsGetImageFromCurrentImageContext()
                   UIGraphicsEndImageContext()
                callback(image!)
            }
          }
        })
  }
}
```
In this code, I can't re-use the traits config ,so I always saved the snapshots from specific running simulator.

Any Ideas?

I think you can define this as a public method: 
```
snapshotView(
          config: .init(safeArea: .zero, size: size ?? view.frame.size, traits: .init()),
          drawHierarchyInKeyWindow: drawHierarchyInKeyWindow,
          traits: traits,
          view: view,
          viewController: .init()
        )
```

**Comment by marcosgriselli** [comment] 2020-09-29 11:59
@Irelylnny not sure if it fits your specific needs but there's a `.wait` strategy which will delay the snapshot, letting your view controller perform the animations: 
https://github.com/pointfreeco/swift-snapshot-testing/commit/69d029ca721fed87c8a655377716c69ebe985e4f

Also, there's a related conversation on #173.

**Comment by stephencelis** [comment] 2021-08-16 22:24
Closing this as a dupe of #173. We'd like to make the VC strategy a bit more flexible in the future, but haven't had time to expose such hooks, sorry!

**Closed by stephencelis** 2021-08-16 22:24 UTC
Labels: duplicate
