### ISSUE TITLE
Diffing.image(precision:) should be scale aware

### ISSUE THREAD

**Issue by moritzsternemann** [pointfreeco/swift-snapshot-testing#324] opened 2020-05-05 12:54 UTC
While working with snapshot-tests on a large scale, we resorted to lowering the snapshot resolution in some cases to improve performance. This was achieved by reducing the `displayScale` of the trait collection passed to the `Snapshotting.image()` method.

While the results are as expected, when the snapshot-test fails, the attached diff is incorrect.

### Example
Notice the *plus icon* in the corner, which has the correct size while the *i icon* is scaled up.
![difference_3_56070A52-D4ED-4B9D-B02B-696523A763C6](https://user-images.githubusercontent.com/3034168/81066457-66b0c980-8edd-11ea-9dba-ed02832e0f09.png)

### Solution
I noticed that the image diffing strategy uses the `UIScreen.main.scale` constant to load the reference snapshot from disk ([Sources/SnapshotTesting/Snapshotting/UIImage.swift#L16](https://github.com/pointfreeco/swift-snapshot-testing/blob/master/Sources/SnapshotTesting/Snapshotting/UIImage.swift#L16)).
This causes the reference image being a different size the new snapshot when creating the diff, which results in a pretty much useless XCTestAttachment.

I suggest to resolve this by passing the `displayScale` from the trait collection through to the image diffing strategy. I prepared the necessary changes and would like to open a PR as soon as possible if nobody finds anything wrong with my approach.

**Comment by stephencelis** [comment] 2020-05-06 19:41
This sounds good to us! Thanks for exploring the solution.

**Comment by stephencelis** [comment] 2020-05-07 17:07
@moritzsternemann This also appears to be a dupe of #243, right? I'm going to close this, but feel free to reopen if you think the issues are distinct.

**Closed by stephencelis** 2020-05-07 17:07 UTC

**Comment by moritzsternemann** [comment] 2020-05-11 08:18
@stephencelis yes, I totally missed that!
